CREATE TABLE "GCG_4259_CREW_SCHED"(
 "REC_ID" BIGINT NOT NULL ,
 "EMPLOYEE" CHAR(5) NOT NULL ,
 "NAME" CHAR(30),
 "WORK_CENTER" CHAR(4) NOT NULL ,
 "SCHED_DATE" DATE NOT NULL ,
 "CREW_LEADER" BIT NOT NULL ,
 "SHIFT" CHAR(1));
